# Generated by Django 4.2.7 on 2023-12-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
