# Generated by Django 4.2.7 on 2023-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_wishlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
