# Generated by Django 4.2.7 on 2023-11-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_wishlist_variant_alter_wishlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
    ]
