# Generated by Django 4.2.7 on 2023-11-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_wishlist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
