# Generated by Django 4.2.7 on 2023-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_color_color_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='tag_color',
            field=models.CharField(choices=[('#FF0000', 'red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFC0CB', 'Yellow')], default='#FF0000', max_length=7),
        ),
    ]
