# Generated by Django 4.2.7 on 2023-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_color_add_color_alter_color_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='add_color',
            field=models.CharField(choices=[('#FF0000', 'Hot'), ('#00FF00', 'Sale'), ('#0000FF', 'Offer'), ('#FFC0CB', 'Nice')], default='#FF0000', max_length=120),
        ),
    ]
