# Generated by Django 4.2.7 on 2023-11-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_color_add_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='add_color',
            field=models.CharField(max_length=120),
        ),
    ]
