# Generated by Django 4.2.7 on 2023-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_color_tag_color_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
