# Generated by Django 4.2.7 on 2023-11-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_productimage_color_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product_pro',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product'),
            preserve_default=False,
        ),
    ]
