# Generated by Django 4.2.7 on 2023-11-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_title_product_name_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
