# Generated by Django 4.2.7 on 2023-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_name_subcategory_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
