# Generated by Django 4.2.7 on 2023-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='names',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=150),
        ),
    ]
