# Generated by Django 4.2.7 on 2023-11-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
