# Generated by Django 4.2.7 on 2023-11-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
