# Generated by Django 4.2.7 on 2023-12-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_names_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
