# Generated by Django 4.2.7 on 2023-12-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='names_add',
        ),
    ]
