# Generated by Django 4.2.7 on 2023-12-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_addprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addprofile',
        ),
    ]
